name: CI

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Install the correct version of node
      - name: Detect Node version
        run: echo "##[set-output name=version;]$(cat .nvmrc)"
        id: nvmrc
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "${{ steps.nvmrc.outputs.version }}"

      # Install lerna
      - name: Install lerna
        run: npm i lerna -g

      # Install dependencies
      - name: Install dependencies
        run: lerna bootstrap --no-ci

      # Run tests
      - name: Run tests
        run: npm test
